name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: version (1.2.3)
        required: true
        type: string

jobs:
  npm-publish:
    env:
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions"

      - run: yarn install --immutable --immutable-cache
      - run: yarn publish --new-version "${{ inputs.version }}"
      - run: git push --all --follow-tags


  docker-publish:
    runs-on: ubuntu-latest

    needs: npm-publish

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: uglydonkey/gmail-backup:${{ inputs.version }}


  create-gh-release:
    runs-on: ubuntu-latest

    needs:
      - npm-publish
      - docker-publish

    steps:
      - uses: actions/checkout@v3
      - run: gh release create "v${{ inputs.version }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
